<?php

namespace ContainerNexaGPr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O8mYDkOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o8mYDkO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o8mYDkO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.o8mYDkO.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.o8mYDkO": it references class "App\\Entity\\Article" but no such service exists.'],
            'em' => ['privates', '.errored.oOa_jbJ', NULL, 'Cannot determine controller argument for "App\\Controller\\EditController::article_edit()": the $em argument is type-hinted with the non-existent class or interface: "App\\Controller\\EntityManagerInterface". Did you forget to add a use statement?'],
        ], [
            'article' => 'App\\Entity\\Article',
            'em' => '?',
        ]);
    }
}
