<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR1aNKzx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR1aNKzx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR1aNKzx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR1aNKzx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR1aNKzx\App_KernelDevDebugContainer([
    'container.build_hash' => 'R1aNKzx',
    'container.build_id' => '15f0b2e6',
    'container.build_time' => 1682251330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR1aNKzx');
