<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container18ZW1qx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container18ZW1qx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container18ZW1qx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container18ZW1qx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container18ZW1qx\App_KernelDevDebugContainer([
    'container.build_hash' => '18ZW1qx',
    'container.build_id' => '94374b12',
    'container.build_time' => 1682276437,
], __DIR__.\DIRECTORY_SEPARATOR.'Container18ZW1qx');
