<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL1Sjxhe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL1Sjxhe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL1Sjxhe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL1Sjxhe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL1Sjxhe\App_KernelDevDebugContainer([
    'container.build_hash' => 'L1Sjxhe',
    'container.build_id' => '837d722d',
    'container.build_time' => 1682195050,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL1Sjxhe');
