<?php

namespace ContainerM5ghriz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EeU9E_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ee_u9E.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ee_u9E.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.ee_u9E..App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.ee_u9E.": it references class "App\\Entity\\Article" but no such service exists.'],
            'emi' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'manager' => ['privates', '.errored.jgZnttT', NULL, 'Cannot determine controller argument for "App\\Controller\\EditController::article_edit()": the $manager argument is type-hinted with the non-existent class or interface: "Doctrine\\Persistance\\ObjectManager".'],
        ], [
            'article' => 'App\\Entity\\Article',
            'emi' => '?',
            'manager' => '?',
        ]);
    }
}
