<?php

namespace ContainerM5ghriz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_JgZnttTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.jgZnttT' shared service.
     *
     * @return \Doctrine\Persistance\ObjectManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\EditController::article_edit()": the $manager argument is type-hinted with the non-existent class or interface: "Doctrine\\Persistance\\ObjectManager".');
    }
}
